### ISSUE TITLE
Serving Drinks Scenario

### ISSUE THREAD

**Issue by henrikschnor** [b-it-bots/mas_domestic_robotics#109]
This is kind of a meta issue for the "Serving Drinks" scenario of RoboCup 2019 to keep track of what needs to be done. I will open more issues for every point listed below.

In "Serving Drinks" the robot has to find all party guests without a drink, take orders and deliver the drinks.

### Things to clarify

1. Decide how to deliver drinks: The robot can either hand over drinks or deliver them with an attached tray. If we use the tray, we need an extra action for detecting if the guest takes the wrong drink. Do we have a tray at all? If we hand over the drink (from a tray, or directly from the bar? -> clarify), we need to implement an action for that as well.
2. Implementation design choice: Should people be actively detected (i.e. should we implement an action for that) or should we passively always try to detect people and store information about them (location, attributes) in the knowledge base to be retrieved when needed? This might be related: #73

### To do

- [x] Create a state machine for the scenario (see #106)
- [ ] Perception (todo: clarification, create issues)
  - [ ] Create action "find_people" for finding all persons in a room / in front of the robot, also remember their faces and possibly other attributes like clothing or what they are holding (identify if holding a drink)
    - [ ] Component to turn head to a certain point (see #111)
    - [ ] Recognize people (see #26)
    - [ ] Recognize if a person has a drink
  - [ ] Train object recognition with drinks we need to identify
- [ ] Create action "dialogue" for having simple conversations with people. Integrate NLP/Rasa for this (todo: create issue)
  - [ ] ROS Wrapper for Rasa NLU (see #84)
  - [ ] Implement Rasa Core (see #103)
  - [ ] Store speech relevant information in an ontology (see #74)
- [ ] Manipulation
  - [ ] Create a behavior for picking up specific objects from a table
  - [ ] Create an action (or behavior) for handing over objects. Maybe we can just use the "place_action" for this.
- [ ] Create action "choose_action" for serving drinks, to decide what the robot is going to do next (get order / get drink / is done)

**Comment by argenos** [comment]
Can you please update the to-dos for this issue?
