### ISSUE TITLE
Take out the garbage

### ISSUE THREAD

**Issue by robertocaiwu** [b-it-bots/mas_domestic_robotics#110]
This issue is created to keep track of the progress towards completing the _Take out the garbage_ task.

## Main goal

The robot takes out the trash bags from the two bins in the apartment and move them into a specified collection zone.

### To do list:

- [x] Create a state machine for the execution_manager [#107]
- [ ] Component to turn head to a certain point [#111]
- Perception
    - [ ] Recognize if object is a bin [#112]
    - [ ] Recognize if there is a lid on the bin[#113]
    - [ ] Recognize if the bin is empty or not [#114]
    - [ ] Dectect where to grasp the trash bag from. [#115]
- Manipulation
     - [ ] DMP for up and down motion [#100]
     - [ ] How to grasp a trash bag
     - [ ] Grasp verification

**Comment by alex-mitrevski** [comment]
@robertocaiwu Grasp verification can in theory be done (there is code for that in the `mas_hsr_gripper_controller` package in the `mas_hsr` repository), but the verification depends on an object-specific threshold. This will thus need some testing.
